// ignore_for_file: file_names

import 'package:get/get.dart';

class LanguageStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Splash Screen': 'Splash Screen',
          'Profile': 'Profile',
          'Email': "Email",
          'Bio': "Bio",
          'Language change': 'Language change',
          'English': 'English',
          'Urdu': 'Urdu',
          'Hindhi': 'Hindhi',
          "Gender": 'Gender',
          'Account Type': "Account Type",
          'Logout': 'Logout',
          'Edit Profile': 'Edit Profile',
          'name': 'name',
          'Saved': 'Saved',
          'Data Changed Successfully': 'Data Changed Successfully',
          'Change Password': 'Change Password',
          'Password Change Attemp': 'Password Change Attemp',
          'An email has been sent to your Email, You can change the Password from there':
              'An email has been sent to your Email, You can change the Password from there',
          'Save': 'Save',
          'Male': "Male",
          'Female': "Female",
          "Lawyer's App": "Lawyer's App",
          "Already have an account?": "Already have an account?",
          "Login here": "Login here",
          "Welcome Back !": "Welcome Back !",
          "Create an acoount": "Create an acoount",
          'Password': "Password",
          "Confirm Password": "Confirm Password",
          "Password Miss Matched": "Password Miss Matched",
          "Both Passwords should match": "Both Passwords should match",
          "Signup": "Signup",
          "Client User": "Client User",
          "Advocate": "Advocate",
          "Dont have any account": "Dont have any account",
          "Signup here": "Signup here",
          "Login to your account": "Login to your account",
          "Login": "Login",
          "Complete Profile": "Complete Profile",
          "Upload image": "Upload image",
          "Enter Correct Name": "Enter Correct Name",
          "Full Name": "Full Name",
          "Submit": "Submit",
          "try another email": "try another email",
          "User Logged in": 'User Logged in',
          "No Implementation for Advocate so far":
              "No Implementation for Advocate so far",
          "Resolve the Issue": "Resolve the Issue",
          "Sign Out": "Sign Out",
          "User has been SignOut!": "User has been SignOut!",
          "Entered all the data": "Entered all the data",
          "Missing Fields": "Missing Fields",
          "Profile Created": "Profile Created",
          "Profile has been Successfully created":
              "Profile has been Successfully created",
          "Choose Photo": "Choose Photo",
          "Select from Gallery": "Select from Gallery",
          "Take a Photo": "Take a Photo",
          'Select Lawyers': 'Select Lawyers',
          'Inbox': 'Inbox',
          'Lawyers': 'Lawyers',
          'Type a messgae ...': 'Type a messgae ...'
        },
        'hi_IN': {
          'HomePage': 'मुखपृष्ठ',
          'Localization': 'स्थानीयकरण',
          'Add Teacher App': "शिक्षक ऐप जोड़ें",
          'Counter App': "काउंटर ऐप",
          'Language change': 'भाषा परिवर्तन',
          'Urdu': 'اردو',
          'English': 'انگریزی',
          'Hindhi': 'ہندی',
          'Splash Screen': 'स्प्लैश स्क्रीन',
          'Profile': 'प्रोफ़ाइल',
          'Email': "ईमेल",
          'Bio': "जैव",
          "Gender": 'लिंग',
          'Account Type': "खाता टाइपर",
          'Logout': 'लॉग आउट',
          'Edit Profile': 'प्रोफ़ाइल संपादित करें',
          'name': 'नाम',
          'Saved': 'बचाया',
          'Data Changed Successfully': 'डेटा सफलतापूर्वक बदला गया',
          'Change Password': 'पासवर्ड बदलें',
          'Password Change Attemp': 'पासवर्ड बदलने का प्रयास',
          'An email has been sent to your Email, You can change the Password from there':
              'आपके ईमेल पर एक ईमेल भेजा गया है, आप वहां से पासवर्ड बदल सकते हैं',
          'Save': 'बचाना',
          'Male': "पुरुष",
          'Female': "महिला",
          "Lawyer's App": "वकील का ऐप",
          "Already have an account?": "क्या आपके पास पहले से एक खाता मौजूद है?",
          "Login here": "यहां लॉगिन करें",
          "Welcome Back !": "वापसी पर स्वागत है !",
          "Create an acoount": "एक खाता बनाएं",
          'Password': "पासवर्ड",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Password Miss Matched": "पासवर्ड मिस मैच हुआ",
          "Both Passwords should match": "दोनों पासवर्ड मेल खाने चाहिए",
          "Signup": "साइन अप करें",
          "Client User": "ग्राहक उपयोगकर्ता",
          "Advocate": "वकील",
          "Dont have any account": "कोई खाता नहीं है",
          "Signup here": "यहां साइन अप करें",
          "Login to your account": "अपने अकाउंट में लॉग इन करें",
          "Login": "लॉग इन करें",
          "Complete Profile": "संपूर्ण प्रोफ़ाइल",
          "Upload image": "तस्विर अपलोड करना",
          "Enter Correct Name": "सही नाम दर्ज करें",
          "Full Name": "पूरा नाम",
          "Submit": "जमा करना",
          "try another email": "कोई अन्य ईमेल आज़माएँ",
          "User Logged in": 'उपयोगकर्ता लॉग इन हुआ',
          "No Implementation for Advocate so far":
              "अधिवक्ता के लिए अब तक कोई कार्यान्वयन नहीं",
          "Resolve the Issue": "मामले को हल करो",
          "Sign Out": "साइन आउट",
          "User has been SignOut!": "उपयोगकर्ता साइनआउट हो गया है!",
          "Entered all the data": "सारा डेटा दर्ज किया",
          "Missing Fields": "गुम फ़ील्ड्स",
          "Profile Created": "प्रोफ़ाइल बनाई गई",
          "Profile has been Successfully created":
              "प्रोफ़ाइल सफलतापूर्वक बनाई गई है",
          "Choose Photo": "तस्विर का चयन करो",
          "Select from Gallery": "गैलरी से चयन करें",
          "Take a Photo": "एक तस्वीर लें",
          'Select Lawyers': 'वकील का चयन करें',
          'Inbox': 'इनबॉक्स',
          'Lawyers': 'वकील',
          'Type a messgae ...': 'एक संदेश टाइप करें...',
        },
        'ur_PK': {
          'HomePage': 'ہوم پیج',
          'Localization': 'لوکلائزیشن',
          'Add Teacher App': "ٹیچر ایپ شامل کریں۔",
          'Counter App': "کاؤنٹر ایپ",
          'Language change': 'زبان کی تبدیلی',
          'Hindhi': 'ہندی',
          'Urdu': 'اردو',
          'English': 'انگریزی',

          'Splash Screen': 'سپلیش سکرین',
          'Profile': 'پروفائل',
          'Email': "ای میل",
          'Bio': "بایو",
          "Gender": 'صنف',
          'Account Type': "اکاؤنٹ کی اقسام",
          'Logout': 'لاگ آوٹ',
          'Edit Profile': 'پروفائل میں ترمیم کریں',
          'name': 'نام',
          'Saved': 'محفوظ کیا گیا۔',
          'Data Changed Successfully': 'ڈیٹا کامیابی سے تبدیل ہو گیا۔',
          'Change Password': 'پاس ورڈ تبدیل کریں',
          'Password Change Attemp': 'پاس ورڈ تبدیل کرنے کی کوشش',
          'An email has been sent to your Email, You can change the Password from there':
              'آپ کے ای میل پر ایک ای میل بھیجی گئی ہے، آپ وہاں سے پاس ورڈ تبدیل کر سکتے ہیں۔',
          'Save': 'محفوظ کریں۔',
          'Male': "مرد",
          'Female': "عورت",
          "Lawyer's App": "وکیل کی ایپ",
          "Already have an account?": "پہلے سے ہی اکاؤنٹ ہے؟",
          "Login here": "یہاں لاگ ان کریں۔",
          "Welcome Back !": "خوش آمدید !",
          "Create an acoount": "ایک اکاونٹ بنائیں",
          'Password': "پاس ورڈ",
          "Confirm Password": "پاس ورڈ کی تصدیق کریں۔",
          "Password Miss Matched": "پاس ورڈ مس میچڈ",
          "Both Passwords should match": "دونوں پاس ورڈز مماثل ہونے چاہئیں",
          "Signup": "سائن اپ",
          "Client User": "کلائنٹ صارف",
          "Advocate": "وکیل",
          "Dont have any account": "کوئی اکاؤنٹ نہیں ہے۔",
          "Signup here": "یہاں سائن اپ کریں۔",
          "Login to your account": "آپ کے اکاؤنٹ میں لاگ ان کریں",
          "Login": "لاگ ان کریں",
          "Complete Profile": "مکمل پروفائل",
          "Upload image": "تصویر انٹرنیٹ پر ڈالنا",
          "Enter Correct Name": "درست نام درج کریں۔",
          "Full Name": "پورا نام",
          "Submit": "جمع کرائیں",
          "try another email": "ایک اور ای میل کی کوشش کریں",
          "User Logged in": 'صارف لاگ ان ہوا۔',
          "No Implementation for Advocate so far":
              "ابھی تک وکیل کے لیے کوئی عمل درآمد نہیں ہوا۔",
          "Resolve the Issue": "مسئلہ حل کریں۔",
          "Sign Out": "باہر جائیں",
          "User has been SignOut!": "صارف کو سائن آؤٹ کر دیا گیا ہے!",
          "Entered all the data": "تمام اعداد و شمار درج کئے",
          "Missing Fields": "لاپتہ فیلڈز",
          "Profile Created": "پروفائل بنایا گیا۔",
          "Profile has been Successfully created":
              "پروفائل کامیابی کے ساتھ بن گیا ہے۔",
          "Choose Photo": "تصویر کا انتخاب کریں۔",
          "Select from Gallery": "گیلری سے منتخب کریں۔",
          "Take a Photo": "ایک تصویر لے لو",

          'Select Lawyers': 'وکیل منتخب کریں۔',
          'Lawyers': 'وکلاء',

          'Inbox': 'انباکس',
          'Type a messgae ...': 'ایک میسج ٹائپ کریں...',

          // 'English':''
        },
      };
}
