// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYs4d4zhw77EkEyDA1HQ04KMOq0LYIlS4',
    appId: '1:847118228523:web:a6ba86680304ce701b1e6e',
    messagingSenderId: '847118228523',
    projectId: 'lawyers-app-64344',
    authDomain: 'lawyers-app-64344.firebaseapp.com',
    storageBucket: 'lawyers-app-64344.appspot.com',
    measurementId: 'G-BC1VFMZ71E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY3j-kuqYGewZ1qfxUhp16NnQ8PcuEGlA',
    appId: '1:847118228523:android:b49f91f33d43e7ca1b1e6e',
    messagingSenderId: '847118228523',
    projectId: 'lawyers-app-64344',
    storageBucket: 'lawyers-app-64344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl9pXtIBARExgxKulWjq0ycDVaPJFveDk',
    appId: '1:847118228523:ios:decd735bbda165a21b1e6e',
    messagingSenderId: '847118228523',
    projectId: 'lawyers-app-64344',
    storageBucket: 'lawyers-app-64344.appspot.com',
    iosBundleId: 'com.example.laywersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl9pXtIBARExgxKulWjq0ycDVaPJFveDk',
    appId: '1:847118228523:ios:94851d5e087f29671b1e6e',
    messagingSenderId: '847118228523',
    projectId: 'lawyers-app-64344',
    storageBucket: 'lawyers-app-64344.appspot.com',
    iosBundleId: 'com.example.laywersApp.RunnerTests',
  );
}
